### ISSUE TITLE
Allow local variables to be used in lambda functions 

### ISSUE THREAD

**Issue by Pushpavel** [pankleks/EventLoop#1]
**ERROR**
no suitable conversion function from "lambda [](int count)->void" to "handler_1 *" exists.

**Related Link**
[https://stackoverflow.com/questions/59111610/how-do-you-declare-a-lambda-function-using-typedef-and-then-use-it-by-passing-to](https://stackoverflow.com/questions/59111610/how-do-you-declare-a-lambda-function-using-typedef-and-then-use-it-by-passing-to)

```cpp
#include <Arduino.h>
#include <EventLoop.h>

EVENT_LOOP; // redefine void loop()

void setup()
{
    bool state = false;
    pinMode(LED_BUILTIN, OUTPUT);

    // set interval
    elp.interval(
        [&state](int count)
        {
            // blink every 500ms
            state = !state;
            digitalWrite(LED_BUILTIN, state);
        },
        500);
}```

**Comment by pankleks** [comment]
done in v1.2.0 - except AVR architecture
